[package]
name = "nostr-keyring"
version = "0.32.0"
edition = "2021"
description = "Nostr Keyring"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "keyring"]

[dependencies]
#keyring = "2.3" # TODO: use only for ios target?
nostr = { workspace = true, default-features = false, features = ["std", "nip49"] }
thiserror.workspace = true

[target.'cfg(not(all(target_os = "android", target_os = "ios")))'.dependencies]
dirs = "5.0"
